name: app_eventos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Íconos estilo iOS
  cupertino_icons: ^1.0.8

  # Firebase y Firestore (versiones compatibles)
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Puedes agregar imágenes aquí si las necesitas
  # assets:
  #   - images/
